### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by miguelpaz** [macloo/html_css_templates#1]
Hi Mindy: Is this project under any license (Creative Commons, MIT, etc.)? I want to fork and credit properly. But I don't see license details in the repository.

**Comment by macloo** [comment]
I will fix. Let me take a look.

**Comment by macloo** [comment]
Okay, @miguelpaz -- I put an MIT License on it. Be warned some of those files are pretty OLD! Feel free to submit pull requests if you think it's worthwhile.

**Comment by miguelpaz** [comment]
I will check it and if I fork and make updates I will send a pull request. Thanks!
